{% set name = "python-fsutil" %}
{% set version = "0.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4cc78b9a1e64011cb4fdaeba531e457e649a6a9a560424e841426e47f3a153ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - fsutil
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fabiocaccamo/python-fsutil
  summary: file-system utilities for lazy devs.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pmrowla
    - efiop
    - shcheklein
    - fabiocaccamo
